import type {UIMessage} from "@ai-sdk/react"

import type {SessionContextMetadata, SessionContextState, SessionDetails, SessionSummary,} from "./types"

export const generateMessageId = () => {
    if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
        return crypto.randomUUID()
    }

    return Math.random().toString(36).slice(2)
}

export const summarizeSession = (session: SessionDetails): SessionSummary => ({
    id: session.id,
    label: session.label,
    createdAt: session.createdAt,
    updatedAt: session.updatedAt,
    project: session.project,
    workspace: session.workspace,
    repository: session.repository,
    branch: session.branch,
    context: {
        folderExists: session.context.folderExists,
        truncated: session.context.truncated,
        hasBootstrap: session.context.hasBootstrap,
        fileCount: session.context.files.length,
    },
    persist: {
        hasPendingChanges: session.persist.hasPendingChanges,
        draftCount: session.persist.draftCount,
        pr: session.persist.pr,
    },
})

export const buildSessionContextPayload = (
    session: SessionDetails,
    messageId: string,
): {
    message: UIMessage
    metadata: SessionContextMetadata
    state: SessionContextState
} => {
    const headerLines = [
        `Project: ${session.project.name}${
            session.project.key ? ` (${session.project.key})` : ""
        }`,
        session.workspace.name
            ? `Workspace: ${session.workspace.name}`
            : session.workspace.slug
                ? `Workspace: ${session.workspace.slug}`
                : null,
        `Repository: ${session.repository.name} (${session.repository.slug})`,
        `Branch: ${session.branch.name}`,
    ].filter(Boolean) as string[]

    const files = session.context.files
    let state: SessionContextState = "ready"
    const sections: string[] = []

    if (!session.context.folderExists) {
        state = "missing"
        sections.push(
            `${headerLines.join(
                "\n",
            )}\n\nThe persistency layer was not found for this branch. This session will start without repository context.`,
        )
    } else if (files.length === 0) {
        state = "empty"
        const bootstrapNote = session.context.hasBootstrap
            ? ""
            : "\nThe ai-bootstrap.mdc file was not found."
        sections.push(
            `${headerLines.join(
                "\n",
            )}\n\nThe persistency layer does not contain any .mdc files.${bootstrapNote}\nThis session will start without repository context.`,
        )
    } else {
        const notes: string[] = []
        if (!session.context.hasBootstrap) {
            notes.push(
                "Warning: ai-bootstrap.mdc was not found. Results may be limited.",
            )
        }
        if (session.context.truncated) {
            notes.push(
                "Additional files exist in the persistency layer but were omitted to respect the limit.",
            )
        }

        const fileSections = files
            .map((file) => {
                const lines = [
                    `### ${file.path}`,
                    "```",
                    file.content,
                    "```",
                ]
                if (file.truncated) {
                    lines.push("_Note: File content truncated to 100kB for preview._")
                }
                return lines.join("\n")
            })
            .join("\n\n")

        sections.push(
            [
                headerLines.join("\n"),
                `Loaded files: ${files.length}`,
                notes.length > 0 ? notes.join(" ") : null,
                "",
                fileSections,
            ]
                .filter((part) => part != null && part.length > 0)
                .join("\n\n"),
        )
    }

    const metadata: SessionContextMetadata = {
        fileCount: files.length,
        truncated: session.context.truncated,
        folderExists: session.context.folderExists,
        hasBootstrap: session.context.hasBootstrap,
    }

    const contextStatus =
        state === "ready" ? "ready" : state === "missing" ? "missing" : "empty"

    const message: UIMessage = {
        id: messageId,
        role: "user",
        parts: [
            {
                type: "text",
                text: sections.join("\n\n"),
            },
        ],
        metadata: {
            source: "bitbucket-ai-folder",
            autoGenerated: true,
            contextStatus,
            context: {
                project: session.project,
                workspace: session.workspace,
                repository: session.repository,
                branch: {
                    name: session.branch.name,
                    isDefault: session.branch.isDefault,
                },
                files,
                folderExists: session.context.folderExists,
                truncated: session.context.truncated,
                hasBootstrap: session.context.hasBootstrap,
            },
        },
    }

    return {message, metadata, state}
}
